### ISSUE TITLE
LEEME

### ISSUE THREAD

**Issue by 01Giovani** [01Giovani/POOII#12]
@Gamzeescript olvide pedirte una forma de contactarte .. en cuanto lea esto porfavor deja un contacto facebook, whatsapp  .. de preferencia fb

por cierto soy de POO2 ..

**Comment by Gamzeescript** [comment]
hola... mi correo es gamzeescript@outlook.com, mandame un email y te mando mi número para WA

**Comment by 01Giovani** [comment]
te envie un correo ..  @Gamzeescript
