### ISSUE TITLE
Modificar estructura del proyecto

### ISSUE THREAD

**Issue by 01Giovani** [01Giovani/POOII#17]
necesitamos que se modifique la estrucutura de carpetas del proyecto .. ya que vamos a usar mvc.. como esta ahorita hay demasiado desorden y no lo podremos implementar de forma correcta 
tiene que quedar de la siguiente forma ....
![avcac](https://cloud.githubusercontent.com/assets/5936005/9502896/1aa070b0-4bf1-11e5-9050-8e2517d8ef91.PNG)

*necesito que dentro de source package crees 3 paquetes -- 
**SistemaVisitasInstitucionales.Core 
**SistemaVisitasInstitucionales.Service
**SistemaVisitasInstitucionales.Data

****dentro de core vas a colocar cada clase que ya esta creada que seria una por cada tabla en nuestra base de datos 
*****dentro de data hay que desglosar la clase controller y crear una clase (NombreDeTabla)Controller.cs por cada tabla en nuestra base de datos

en el package servicios es donde se creara la funcionalidad para cada accion que necesitemos por ejemplo catalogos , reportes  (esto pendiente por el momento)

luego en la raiz de Web Pages creas una carpeta por cada servicio nombrado con el nombre del servicio el formato para los nombres de los servicios es (nombre)Service.cs

esta tarea esta un poco compleja .. por los problemas que pueden haber al tratar de modificar la estructuta de carpetas del proyecto 
sera necesario crear una branch . nombrada MVC esta del estado actual de la master y proceder a realizar los cambios

**Comment by Gamzeescript** [comment]
enterada, yo lo hago.

**Comment by AlonsoRamirez** [comment]
¿En que momento intervengo en el sistema?

**Comment by 01Giovani** [comment]
done
