### ISSUE TITLE
crear interfaz visual

### ISSUE THREAD

**Issue by 01Giovani** [01Giovani/POOII#3]
-crear masterpage de mantenimientos
-crar masterpage de reportes
-pantalla loguin 
-pantalla home de cada tipo de usuario( con las opciones que se indican en el enunciado)

**Comment by Gamzeescript** [comment]
enterada

**Comment by 01Giovani** [comment]
Si queres descargate una de bootstrap para que no trabajes mucho unicamente adecuala la idea es que quede listo para montar la funcionalidad

**Comment by Gamzeescript** [comment]
vaya, yo le implemento bootsttrap

**Comment by 01Giovani** [comment]
Te escribi en fb ... por si no lo leiste .. dije esto  "..algo importante es que no trabajes sobre la master  .. hace fork de ka master y cuando termines la tarea creas un pullrequest a la master"  nosotro estamos utilizando source integrado a git .. por  si quieres probarlo o ya lo usaste antes

**Comment by Gamzeescript** [comment]
heey!! pregunta ¿colores o algo que quieren que le ponga de fondo a las interfaces? ya estoy acabando.

**Comment by 01Giovani** [comment]
complete
